spring.application.name=userservice

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Allow changing the server port via CLI when running multiple instances
server.port=${PORT:8080}
logging.level.net.javacrumbs.shedlock=DEBUG